--CLASE 12 
USE Northwind
GO
--TRANSACCIONES

--TRANSACCIONES AUTOMÁTICAS (AUTOCOMMIT)
--LAS TRANSACCIONES SE APLICAN DE FORMA AUTOMÁTICA SIN NECESIDAD DE CONFIRMARSE
INSERT INTO Customers (CustomerID, CompanyName, ContactTitle, Country)
VALUES 
	('AZFM','AZ Consulting', 'Alejandro Serrano','San José');
GO
--CONSULTA DE DATO
SELECT * FROM Customers
--MODIFICAR DATO EN LA TABLA
UPDATE Customers
	SET CustomerID = 'ASPE'
		WHERE CustomerID = 'AZFM';
GO

--TRANSACCIONES EXPLÍCITAS (REQUIEREN CONFIRMACIÓN)
--TIENEN APERTURA DE TRANSACCIÓN
BEGIN TRANSACTION	
	DELETE FROM Customers	
		WHERE CustomerID = 'ASPE';
GO
--CONSULTA DE DATO
SELECT * FROM Customers

--CONFIRMAR TRANSACCION
COMMIT TRANSACTION
GO
--DESCARTAR TRANSACCION
ROLLBACK TRANSACTION
GO


--CONSULTA DE BLOQUEOS
EXEC sp_lock

--TRANSACCIONES IMPLÍCITAS (REQUIEREN CONFIRMACIÓN)
--TIENEN APERTURA DE TRANSACCIÓN
SET IMPLICIT_TRANSACTIONS ON --CUALQUER OPERACION DE INSERT, UPDATE O DELETE
--LEVANTA UNA TRANSACCION
INSERT INTO Customers (CustomerID, CompanyName, ContactTitle, Country)
VALUES	
	('ASE1','AZ Consulting', 'Alejandro Serrano','San José');
GO

--CONFIRMAR TRANSACCION
COMMIT TRANSACTION
GO
--DESCARTAR TRANSACCION
ROLLBACK TRANSACTION
GO