--CLASE 11 FUNCIONES

--CAMBIO DE BASE DE DATOS
USE Northwind
GO
 
--EXISTEN 3 TIPOS DE FUNCIONES
--ESCALAR, TABLA EN LÍNEA Y TABLA CON MULTIPLES OPERACIONES
--CREAR FUNCION ESCALAR (DEVUELVE UN VALOR)
CREATE FUNCTION FN_IVA (@Monto MONEY)
RETURNS MONEY
AS
	BEGIN
		DECLARE @Impuesto MONEY
		SET @Impuesto = @Monto * 0.13
		RETURN (@Impuesto)
	END;
GO
--USAR LA FUNCION ESCALAR FN_IVA
SELECT ProductName, UnitPrice, DBO.FN_IVA (UnitPrice)
AS IVA
FROM Products;
GO

--ELIMINAR FUNCION
DROP FUNCTION FN_IVA;
GO
--CREAR FUNCION COMISION
CREATE FUNCTION FN_Comision (@Monto MONEY)
RETURNS MONEY
AS
	BEGIN
		DECLARE @Resultado MONEY
		IF @Monto >=250
			BEGIN
				SET @Resultado = @Monto * 0.10
			END	
		ELSE
			BEGIN
				SET @Resultado = 0
			END
	RETURN (@Resultado)
	END;
GO

--USAR LA FUNCION COMISION
SELECT OrderID, ProductID, UnitPrice, Quantity,
UnitPrice * Quantity AS TOTAL, 
DBO.FN_Comision (UnitPrice* Quantity) AS 'COMISION VENDEDOR'
FROM [Order Details]

