--CLASE 10 
USE Normalizar
GO

--CREAR TABLA SIN NORMALIZAR
CREATE TABLE DBO.EMPLEADO
(
	NombreEmpleado NVARCHAR (50),
	Oficina NVARCHAR (50),
	Salario INT,
	SupervisorAsignado NVARCHAR (50),
	FechaIngreso DATE
);
GO

--INSERTAR REGISTROS A LA TABLA EMPLEADO
INSERT INTO DBO.EMPLEADO
VALUES	
	('Pedro Ramirez','Central',100000, 'Marta Solis','2020-01-01'),
	('Carlos Tencio','Central',100000, 'Marta Solis','2020-02-01'),
	('Maria Porras','Heredia',100000, 'Gilberth Mora','2020-03-01'),
	('Keneth Marin','Heredia',100000, 'Gilberth Mora','2020-04-01'),
	('Karla Fallas','Cartago',15000, 'Francisco Tencio','2020-05-01'),
	('Ana Rojas','Cartago',25000, 'Francisco Tencio','2020-06-01');
GO

--CONSULTA DE DATOS DE LA TABLA
SELECT * FROM DBO.EMPLEADO

----------------------------------
--NORMALIZACION DE BASE DE DATOS
----------------------------------

--CREAR TABLA SUCURSAL
CREATE TABLE DBO.SUCURSALES
(
	IDSucursal INT IDENTITY (1,1) NOT NULL,
	NombreSucursal NVARCHAR (20) NOT NULL,
	CONSTRAINT PK_IDSucursal PRIMARY KEY (IDSucursal)
);
GO

--INSERTAR DATOS A LA TABLA SUCURSALES
INSERT INTO DBO.SUCURSALES (NombreSucursal)
SELECT DISTINCT Oficina FROM DBO.EMPLEADO
GO
--CONSULTAR DATOS DE TABLA
SELECT * FROM DBO.SUCURSALES
GO
--CREAR TABLA SUPERVISORES
CREATE TABLE DBO.SUPERVISORES
(
	IDSupervisor INT IDENTITY  (1,1) NOT NULL,
	NombreSupervisor NVARCHAR (60) NOT NULL,
	IDSucursal INT NOT NULL
	CONSTRAINT PK_IDSupervisor PRIMARY KEY (IDSupervisor),
	CONSTRAINT FK_IDSucursal FOREIGN KEY (IDSucursal) REFERENCES DBO.SUCURSALES (IDSucursal)
);
GO

--INSERTAR DATOS A LA TABLA 
INSERT INTO DBO.SUPERVISORES (NombreSupervisor, IDSucursal)
SELECT DISTINCT EMP.SupervisorAsignado, SUC.IDSucursal 
FROM DBO.EMPLEADO AS EMP
JOIN DBO.SUCURSALES AS SUC ON EMP.Oficina = SUC.NombreSucursal

--CONSULTA DE TABLA
SELECT * FROM DBO.SUPERVISORES

--CREAR TABLA DE EMPLEADO TEMPORAL
CREATE TABLE DBO.EMPLEADO_TEMPORAL
(
	IDEmpleado INT IDENTITY	(1,1) NOT NULL,
	NombreEmpleado NVARCHAR (30) NOT NULL,
	ApellidoEmpleado NVARCHAR (30) NOT NULL,
	Salario INT NOT NULL,
	IDSucursal INT NOT NULL,
	IDSupervisor INT NOT NULL,
	CONSTRAINT PK_IDEmpleado PRIMARY KEY (IDEmpleado),
	CONSTRAINT FK_IDSucursalEmp FOREIGN KEY (IDSucursal) REFERENCES DBO.SUCURSALES (IDSucursal),
	CONSTRAINT FK_IDSupervisor FOREIGN KEY (IDSupervisor) REFERENCES DBO.SUPERVISORES (IDSupervisor),
);
GO


--INSERTAR DATOS A LA TABLA 
INSERT INTO DBO.EMPLEADO_TEMPORAL (NombreEmpleado, ApellidoEmpleado, Salario, IDSucursal, IDSupervisor)
SELECT 
	SUBSTRING (NombreEmpleado, 1, CHARINDEX(' ', NombreEmpleado) -1) AS NombreEmpleado,
	SUBSTRING (NombreEmpleado, CHARINDEX(' ', NombreEmpleado), LEN (NombreEmpleado)+ 1) AS ApellidoEmpleado,
	EMP.Salario,
	SUC.IDSucursal,
	SUP.IDSupervisor
FROM DBO.EMPLEADO AS EMP
JOIN DBO.SUCURSALES AS SUC ON EMP.Oficina = SUC.NombreSucursal
JOIN DBO.SUPERVISORES AS SUP ON EMP.SupervisorAsignado = SUP.NombreSupervisor

--CONSULTA DE TABLA
SELECT * FROM DBO.EMPLEADO_TEMPORAL
go
--BORRAR  TABLA SIN NORMALIZAR
DROP TABLE DBO.EMPLEADO
GO
--RENOMBRO TABLA EMPLEADO_TEMPORAL A EMPLEADO
EXEC sp_rename 'EMPLEADO_TEMPORAL', 'EMPLEADO'
GO

--CONSULTAR LAS TABLAS NORMALIZADAS
SELECT * FROM DBO.EMPLEADO
SELECT * FROM DBO.SUCURSALES
SELECT * FROM DBO.Supervisores